### ISSUE TITLE
Published?

### ISSUE THREAD

**Issue by DullReferenceException** [thlorenz/browserify-devdupe#1]
Is this complete and published to NPM? I am unable to install it. It definitely would solve a big problem for me.

**Comment by juliangruber** [comment]
what error do you get?

**Comment by DullReferenceException** [comment]
> npm ERR! 404 no such package available : browserify-devdupe
> npm ERR! 404
> npm ERR! 404 'browserify-devdupe' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by madcapnmckay** [comment]
I'm getting this too. You're on version 0.0.0, did you run npm publish to push it to the registry?

**Comment by thlorenz** [comment]
No never published, I realized it wasn't the best idea (too many caveats).
Do any of you still really need this? I can publish if so.

**Comment by DullReferenceException** [comment]
I ended up switching to WebPack, so not important to me anymore.
